server:
  port: 8082
spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:2412/account-db
    username: postgres
    password: postgres
springdoc:
  show-actuator: true
logging:
  level:
    org.jooq.Constants: WARN
