/*
 * This file is generated by jOOQ.
 */
package ch.pf.pibs.account.jooq;


import ch.pf.pibs.account.jooq.tables.Account;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;
}
