/*
 * This file is generated by jOOQ.
 */
package ch.pf.pibs.account.jooq.tables.pojos;



/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccountDto {

    private Long id;
    private String accountType;
    private String accountOwner;

    public AccountDto() {}

    public AccountDto(AccountDto value) {
        this.id = value.id;
        this.accountType = value.accountType;
        this.accountOwner = value.accountOwner;
    }

    public AccountDto(
        Long id,
        String accountType,
        String accountOwner
    ) {
        this.id = id;
        this.accountType = accountType;
        this.accountOwner = accountOwner;
    }

    /**
     * Getter for <code>public.account.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.account.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.account.account_type</code>.
     */
    public String getAccountType() {
        return this.accountType;
    }

    /**
     * Setter for <code>public.account.account_type</code>.
     */
    public void setAccountType(String accountType) {
        this.accountType = accountType;
    }

    /**
     * Getter for <code>public.account.account_owner</code>.
     */
    public String getAccountOwner() {
        return this.accountOwner;
    }

    /**
     * Setter for <code>public.account.account_owner</code>.
     */
    public void setAccountOwner(String accountOwner) {
        this.accountOwner = accountOwner;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AccountDto other = (AccountDto) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.accountType == null) {
            if (other.accountType != null)
                return false;
        }
        else if (!this.accountType.equals(other.accountType))
            return false;
        if (this.accountOwner == null) {
            if (other.accountOwner != null)
                return false;
        }
        else if (!this.accountOwner.equals(other.accountOwner))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.accountType == null) ? 0 : this.accountType.hashCode());
        result = prime * result + ((this.accountOwner == null) ? 0 : this.accountOwner.hashCode());
        return result;
    }
}
