CREATE SEQUENCE PERSON_SEQ
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE CACHE 1;

CREATE TABLE PERSON
(
    ID          BIGINT  NOT NULL,
    FIRST_NAME  VARCHAR NOT NULL,
    LAST_NAME   VARCHAR NOT NULL,
    PRIMARY KEY (ID)
);