CREATE SEQUENCE ACCOUNT_SEQ
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE CACHE 1;

CREATE TABLE ACCOUNT
(
    ID              BIGINT  NOT NULL,
    ACCOUNT_TYPE    VARCHAR NOT NULL,
    ACCOUNT_OWNER   VARCHAR NOT NULL,
    PRIMARY KEY (ID)
);